<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="welcome-PC" name="com.selenium.framework.datadriven.PortFolio.Test3" tests="1" failures="0" timestamp="20 Mar 2016 12:22:53 GMT" time="2.200" errors="1">
  <testcase name="test3" time="2.200" classname="com.selenium.framework.datadriven.PortFolio.Test3">
    <error type="java.lang.AssertionError" message="Not able to open browser - Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: &#039;2.42.2&#039;, revision: &#039;6a6995d31c7c56c340d6f45a76976d43506cd6cc&#039;, time: &#039;2014-06-03 10:52:47&#039;
System info: host: &#039;welcome-PC&#039;, ip: &#039;192.168.1.6&#039;, os.name: &#039;Windows 7&#039;, os.arch: &#039;amd64&#039;, os.version: &#039;6.1&#039;, java.version: &#039;1.7.0_79&#039;
Driver info: driver.version: RemoteWebDriver">
      <![CDATA[java.lang.AssertionError: Not able to open browser - Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '2.42.2', revision: '6a6995d31c7c56c340d6f45a76976d43506cd6cc', time: '2014-06-03 10:52:47'
System info: host: 'welcome-PC', ip: '192.168.1.6', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_79'
Driver info: driver.version: RemoteWebDriver
	at org.testng.Assert.fail(Assert.java:89)
	at com.selenium.framework.datadriven.TestBase.openBrowser(TestBase.java:143)
	at com.selenium.framework.datadriven.TestBase.doLogin(TestBase.java:217)
	at com.selenium.framework.datadriven.TestBase.doDefaultLogin(TestBase.java:237)
	at com.selenium.framework.datadriven.PortFolio.Test3.test3(Test3.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:842)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:73)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase>
</testsuite>
